function actualBlockName = getActualBlockName(dotBlockName,blockNameList)
% helps to retrive the actual name of the block by giving the name which
% was generated by the "convertBlockNames" function

for listInd = 1:length(blockNameList)
    checkName = blockNameList{1,listInd}{2};
    % Remove the " string from the dotBlockName to avoid the graphviz issue
    dotBlockName = strrep(dotBlockName,'"','');
    % Check for the matching name from the list
    matchName = strcmp(checkName,dotBlockName);
    if matchName
        % Return the actual name
        actualBlockName = blockNameList{1,listInd}{1};
        return;
    else
        actualBlockName = '';
    end
end

end